_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.1
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
activation:
    value: tanh
batch_size:
    value: 32
epochs:
    value: 20
hidden_size:
    value: 32
learning_rate:
    value: 0.0003517680841740224
num_layers:
    value: 3
